stages:
  - test

test:one:
  stage: test
  tags:
    - aws-small
  script:
    - echo "this is base"
    - echo "one1"
    - echo "one2"
    - echo "one3"
    - echo "one4"
    - echo "one5"
    - echo "one6"
    - echo "one7"
    - echo "one8"
    - echo "one9"
    - echo "one10"
    - echo "one11"

test:two:
  stage: test
  tags:
    - aws-small
  script:
    - echo "two1"
    - echo "two2"
    - echo "two3"
    - echo "two4"
    - echo "two5"
    - echo "two6"
    - echo "two7"
    - echo "two8"
    - echo "two9"
